### ISSUE TITLE
Prototype naar HTML

### ISSUE THREAD

**Issue by Keremttc** [Keremttc/the-client-website#1]
Hierbij mijn prototype van TumiMundo.

![WhatsApp Image 2024-09-25 at 11 55 47](https://github.com/user-attachments/assets/26e516f0-3992-44be-be5e-ec09f22ff5c2)

**Comment by Seijno** [comment]
Design ziet er goed uit, code heeft soms wat onnodige wit-ruimte, ook kan je de code meer netjes maken door een duidelijk gebruik te maken van de tabs.

voorbeeld:
<main>
    <div>
        voorbeeld
    </div>
</main

**Comment by Lutrian1** [comment]
In de validator kon ik geen issues vinden. Verder gebruikt de code wat veel wit regels. Had je ook een desktop design? Kon ik niet vinden

**Comment by Safae-e** [comment]
Code ziet er netjes uit! Uit de HTML checker kwamen geen fouten tevoorschijn. Goed gedaan!
